# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-27 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sprite', models.ImageField(upload_to='sprites')),
                ('detalles', models.CharField(max_length=50)),
            ],
        ),
    ]
